### ISSUE TITLE
Weird bug with 'material-community' font

### ISSUE THREAD

**Issue by nghtctrl** [Team-Equipo/client#62]
- https://stackoverflow.com/questions/57349431/error-with-expo-fontfamily-material-community-is-not-a-system-font-and-has-not/61264240#61264240
- Remove material-community font? Removing node_module component is only a temporary fix. People who are testing our app will not know how to fix this.

**Comment by Cobblestone5517** [comment]
Fixed by downgrading `expo-font` module
